name: EA2 - Pipeline
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install pandas openpyxl requests
    - run: python src/ingestion.py
    - run: python src/cleaning.py
